name: Application CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  application-check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Install node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "cache dependencies"
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: "Install dependencies"
        run: npm ci 

      - name: "Linting"
        run: npm run lint


      - name: "Run tests"
        run: npm test

      - name: "Build Application"
        run: npm run build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: github-profile-viewer-build
          path: dist


